### ISSUE TITLE
Fitting relaxed clock models to the BEAST v1.10.5 pre-release?

### ISSUE THREAD

**Issue by guillemmasfiol** [COG-UK/UK-lineage-dynamics-analysis#10]
Hello,

thank you for these astonishing workflows. I am interested in the likelihood methodology you included into @jtmccr1's BEAST v1.10.5 pre-release of ThorneyTreeLikelihood v0.1.0 in order to be able to analyze huge numbers of samples. I could test it and it genuinely worked fine and quick for big datasets.

However, by just looking at the information provided in the 'tutorial' at Beast community for this new method [https://beast.community/thorney_beast](url) it looks to me we can only use a strict clock model for estimating branch lengths. 
I do not see an obvious way for accommodating relaxed models like uncorrelated lognormal relaxed clock. Is it theoretically possible?  How could it be applied?

Thank  you very much!

Guillem

**Comment by jtmccr1** [comment]
Hello Guillem,

I'm happy you've had some success using the method. There is no theoretical reason to only use a strict clock in these instances. It is just the simplest model to implement and the quickest to get up and running. We have recently made a small update to the release that patches a minor bug in the root height estimation present in that release. https://github.com/beast-dev/beast-mcmc/releases/tag/v1.10.5pre_thorney_v0.1.1

That release technically includes the ability to pass the thorneyTreeLikelihood a regular branchRate model like those you use in a standard BEAST run. I see no reason the implementation would not be correct, but you never do I suppose. That code has not been thoroughly tested and so is not mentioned in the release notes.  I would say to use it at your own risk. The xml for doing that is below. I'll add I don't expect these standard approaches, which estimate a rate per branch, would scale very well with large datasets. I think we will have more luck with models like those mentioned in https://academic.oup.com/mbe/article/38/1/307/5877436. These are in progress, but not ready for the big time yet.

Hope this is useful!
Best,
JT

```
    <thorneyTreeLikelihood id="treeLikelihood">
		<constrainedTreeModel idref="treeModel"/>
		
			<!-- The strict clock (Uniform rates across branches)                        -->
		<strictClockBranchRates id="branchRates">
			<rate>
				<parameter id="clock.rate" value="0.0001" lower="0.0"/>
			</rate>
		</strictClockBranchRates>
		
		<branchLengthLikelihood id="branchLengthLikelihood" scale="29903.0"/>
			
		<constrainedBranchLengthProvider scale="29903.0" discrete="true" minBranchlength="0.0">
			<constrainedTreeModel idref="treeModel"/>
			<dataTree>
				<tree idref="dataTree"/>
			</dataTree>
		</constrainedBranchLengthProvider>
	</thorneyTreeLikelihood>
```
