### ISSUE TITLE
BEAST version

### ISSUE THREAD

**Issue by noranekonobokkusu** [COG-UK/UK-lineage-dynamics-analysis#7]
Hello,

I was trying to run an analysis similar to yours and sample SARS-CoV-2 trees from a nonresolved initial topology not using sequence data, but i'm getting errors from BEAST that i cannot understand. Now i've realized i cannot even run the .xml file provided in the repository (e.g. this one https://github.com/COG-UK/UK-lineage-dynamics-analysis/blob/main/analyses/phylogenetic/results/xml/timetrees/A.fixedRootPrior.skygrid-20200720.xml). I tried to use the latest BEAST version available (with ThorneyTreeLikelihood) and I'm getting
<pre>
SEVERE: Parsing error - poorly formed BEAST file, A.fixedRootPrior.skygrid-20200720.xml:
The '<gmrfSkyrideLikelihood>' element, with id, 'skygrid', is incorrectly constructed.
The following was expected:
Exactly one ELEMENT of name intervals REQUIRED containing
    Any number of ELEMENT of type IntervalList REQUIRED

Error thrown at: dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
</pre>

There is even no element called gmrfSkyrideLikelihood in the file!
My guess is that I'm using the wrong version of BEAST but the link towards the commit c8cc55d4 leads nowhere.
How can I make it work?

Thanks!

**Comment by noranekonobokkusu** [comment]
I've also noticed i'm getting a bunch of 'Failed to load parser: ' warnings before it fails to parse an .xml.

**Comment by noranekonobokkusu** [comment]
I have found this branch https://github.com/beast-dev/beast-mcmc/tree/approximateTreeLikelihood but i cannot build it. Is there a built version anywhere?

**Comment by rambaut** [comment]
There is a tutorial on these methods here:
http://beast.community/thorney_beast

It includes a link to a built version of the branch.

**Comment by noranekonobokkusu** [comment]
Thank you Andrew, yes, sorry, I tried that version and I got confused about the difference of operators regarding the 'treeModel.rootHeight' parameter in the tutorial and in the .xml mentioned above. I think I've cleared it for myself now, thank you. I am still getting these warnings. Are those harmless?
<pre> Failed to load parser: New parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator} cannot replace existing parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator}
line = dr.evomodelxml.coalescent.operators.GMRFSkygridBlockUpdateOperatorParser
</pre>

**Comment by jtmccr1** [comment]
Hi @noranekonobokkusu,  Those warnings are harmless and should be removed before the next official release. 

Just to elaborate a bit, the analysis in this repository was run with an earlier implementation of the method described in the tutorial Andrew has linked to above. We have since made significant improvements on the performance. Unfortunately, those gains came at the cost of backward compatibility. The xmls from this repository will run with a built version of the https://github.com/beast-dev/beast-mcmc/tree/approximateTreeLikelihood branch, and are included for transparency and reproducibility purposes. But I would recommend using the tutorial with its accompanying example xml and pre-release if you are interested in using the method on your own data.

If you run into any issues along the way, I'd be happy to continue to chat over on the BEAST user group email list https://groups.google.com/g/beast-users.

**Comment by xieruopeng** [comment]
Hello,

When I run this xml file (https://github.com/COG-UK/UK-lineage-dynamics-analysis/blob/main/analyses/phylogenetic/results/xml/timetrees/A.fixedRootPrior.skygrid-20200720.xml) using this version of Beast (https://github.com/beast-dev/beast-mcmc/releases/tag/v1.10.5pre_thorney_v0.1.1), it still reports this issuse:

![image](https://user-images.githubusercontent.com/24712888/117248134-064ac400-ae72-11eb-9747-894312ccac40.png)

**Comment by xieruopeng** [comment]
Isn't it the built version for this branch (https://github.com/beast-dev/beast-mcmc/tree/approximateTreeLikelihood). How can I build this branch by myself?

Thanks

**Comment by bingyinglee** [comment]
> Thank you Andrew, yes, sorry, I tried that version and I got confused about the difference of operators regarding the 'treeModel.rootHeight' parameter in the tutorial and in the .xml mentioned above. I think I've cleared it for myself now, thank you. I am still getting these warnings. Are those harmless?
> 
>  Failed to load parser: New parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator} cannot replace existing parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator}
> line = dr.evomodelxml.coalescent.operators.GMRFSkygridBlockUpdateOperatorParser

sorry, did you run the A.fixedRootPrior.skygrid-20200720.xml successfully by BEASTv.1.10.5pre_thorney_v0.1.1(https://github.com/beast-dev/beast-mcmc/releases/tag/v1.10.5pre_thorney_v0.1.1)？I am still getting the warning: 
Exactly one ELEMENT of name intervals REQUIRED containing
    Any number of ELEMENT of type IntervalList REQUIRED
